---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: '1503774'
_src_path: ./
description: Nest project example 🐈
docs: true
docsurl: https://quickplates.github.io/nest-example
projectname: nest-example
registry: true
username: quickplates
