# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 03b969c
_src_path: ./
accountname: quickplates
description: NestJS service example 🐈
docs: true
docsurl: https://quickplates.github.io/nest-example
envprefix: NEST_EXAMPLE
imagename: services/nest-example
port: 3000
registry: true
releases: true
reponame: nest-example
repourl: https://github.com/quickplates/nest-example
servicename: nest-example
